name: Validate T-SQL script

on: 
  push:
    branches: 
    - main
    paths:
    - '**.sql'

jobs:
  install-sql-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Start SQL Server container
      run: |
        docker run -d \
        --name sqlserver \
        -e 'ACCEPT_EULA=Y' \
        -e 'SA_PASSWORD=Passw0rd11>' \
        -p 1433:1433 \
        mcr.microsoft.com/mssql/server:2019-latest
    - name: Wait for SQL Server to start
      run: sleep 30
    - name: Run T-SQL script
      run: |
        for file in *.sql
        do
          echo "Executing $file..."
          sqlcmd -S localhost -U SA -P 'Passw0rd11>' -b -i $file
        done
